# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    env:
      CDN_ACCESS_KEY_ID: ${{ secrets.CDN_ACCESS_KEY_ID }}
      CDN_ACCESS_KEY_SECRET: ${{ secrets.CDN_ACCESS_KEY_SECRET }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn config set registry https://registry.npmjs.org
      - name: Run unit tests
        run: yarn install && yarn test
      - name: Build
        run: yarn build
      - name: Install @serverless-devs/s
        run: yarn global add @serverless-devs/s
      - name: Generate cdn config
        run: s config add --access cdn --AccessKeyID ${{ secrets.CDN_ACCESS_KEY_ID }} --AccessKeySecret ${{ secrets.CDN_ACCESS_KEY_SECRET }} -f
      - name: Run e2e test
        run: yarn test:e2e
